# Generated by Django 4.2.7 on 2023-11-11 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_magazine_app', '0004_remove_userdetails_id_alter_userdetails_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_magazine_app.userdetails'),
        ),
    ]
